FROM jenkins/jenkins:lts-jdk17

USER root

# Zainstaluj Docker CLI i dodaj użytkownika jenkins do grupy docker
RUN apt-get update && \
    apt-get install -y docker.io && \
    usermod -aG docker jenkins

USER jenkins
