# Bazowy obraz Node.js + JDK17
FROM node:18-alpine

# Zainstaluj Docker CLI
USER root
RUN apk add --no-cache docker-cli

# Użytkownik Jenkins (albo zostaw root, jeśli potrzebujesz dostępu do dockera.sock)
RUN addgroup -S docker && adduser jenkins docker

# Przejdź na użytkownika (opcjonalnie)
USER node
